"""
Copyright to FOA Authors ICML 2024
"""
import torch
import torch.nn as nn
import torch.jit

from models.vpt import PromptViT
import cma
import numpy as np
from quant_library.quant_layers.matmul import *

class CMA_Collect_Features(nn.Module):
    """
    FOA variants which stores features for interval update
    """
    def __init__(self, model:PromptViT, fitness_lambda=0.4, interval=64):
        super().__init__()

        self.model = model
        self.fitness_lambda = fitness_lambda
        self.es = self._init_cma()

        self.best_prompts = model.prompts
        self.best_loss = np.inf

        self.hist_stat = None
        self.cur_prompts = self.es.ask() + [model.prompts.flatten().cpu()]
        # interval update
        self.collected_features = None
        self.collected_outputs = None
        self.interval = interval

    def _init_cma(self):
        """CMA-ES initialization"""
        dim = self.model.prompts.numel()
        popsize = 27 # which is equal to 4 + 3 * np.log(dim) when #prompts=3
        cma_opts = {
            'seed': 2020,
            'popsize': popsize,
            'maxiter': -1,
            'verbose': -1,
        }
        es = cma.CMAEvolutionStrategy(dim * [0], 1, inopts=cma_opts)
        self.popsize = es.popsize
        return es
    
    def _update_hist(self, batch_mean):
        """Update overall test statistics, Eqn. (9)"""
        if self.hist_stat is None:
            self.hist_stat = batch_mean
        else:
            self.hist_stat = 0.9 * self.hist_stat + 0.1 * batch_mean
                
    def _get_shift_vector(self):
        """Calculate shift direction, Eqn. (8)"""
        if self.hist_stat is None:
            return None
        else:
            return self.train_info[1][-768:] - self.hist_stat

    def forward(self, x):
        """calculating shift direction, Eqn. (8)"""
        shift_vector = self._get_shift_vector()

        e_outputs, features = [], [] 
        for j, prompt in enumerate(self.cur_prompts):
            self.model.prompts = torch.nn.Parameter(torch.tensor(prompt, dtype=torch.float).
                                                        reshape_as(self.model.prompts).cuda())
            self.model.prompts.requires_grad_(False)
            output, e_output, feature = forward_and_get_loss(x, self.model, shift_vector, self.imagenet_mask)
            e_outputs.append(e_output.unsqueeze(0))
            features.append(feature.unsqueeze(0))
        
        e_outputs = torch.cat(e_outputs, dim=0)
        features = torch.cat(features, dim=0)
        self.collect_features_and_outputs(e_outputs, features)
        return output # the last outputs is generated by the currently best prompt
    
    def collect_features_and_outputs(self, e_outputs, features):
        if self.collected_features is None:
            self.collected_outputs = e_outputs
            self.collected_features = features
        else:
            self.collected_outputs = torch.cat([self.collected_outputs, e_outputs], dim=1)
            self.collected_features = torch.cat([self.collected_features, features], dim=1)
            del e_outputs, features

        if self.collected_features.shape[1] >= self.interval:
            self.update_cma()

    def update_cma(self):
        best_loss = np.inf
        losses = []
        for i in range(self.collected_outputs.shape[0]):
            features = self.collected_features[i]
            batch_std, batch_mean = torch.std_mean(features, dim=0)
            std_mse, mean_mse = criterion_mse(batch_std, self.train_info[0]), criterion_mse(batch_mean, self.train_info[1])
            # NOTE: $lambda$ should be 0.2 for ImageNet-R!!
            discrepancy_loss = self.fitness_lambda * (std_mse.sum() + mean_mse.sum()) * self.collected_features.shape[1] / 64

            output = self.collected_outputs[i]
            entropy_loss = softmax_entropy(output).sum()
            loss = discrepancy_loss + entropy_loss

            if best_loss > loss:
                best_loss = loss
                best_prompt = self.cur_prompts[i]
            losses.append(loss.item())

        self.es.tell(self.cur_prompts, losses)
        self.cur_prompts = self.es.ask() + [best_prompt]
        # empty cache
        self.collected_features = None
        self.collected_outputs = None
    
    def obtain_origin_stat(self, train_loader):
        print('===> begin calculating mean and variance')
        features = []
        with torch.no_grad():
            for _, dl in enumerate(train_loader):
                images = dl[0].cuda()
                feature = self.model.layers_cls_features(images)
                features.append(feature)
            features = torch.cat(features, dim=0)
            self.train_info = torch.std_mean(features, dim=0)

        # preparing quantized model for prompt adaptation
        for n, m in self.model.vit.named_modules():
            if type(m) == PTQSLBatchingQuantMatMul:
                m._get_padding_parameters(torch.zeros((1,12,197+self.model.num_prompts,64)).cuda(), torch.zeros((1,12,64,197+self.model.num_prompts)).cuda())
            elif type(m) == SoSPTQSLBatchingQuantMatMul:
                m._get_padding_parameters(torch.zeros((1,12,197+self.model.num_prompts,197+self.model.num_prompts)).cuda(), torch.zeros((1,12,197+self.model.num_prompts,64)).cuda())
        print('===> calculating mean and variance end')

    def reset(self):
        self.es = self._init_cma()
        self.hist_stat = None
        self.collected_features =  None
        self.collected_outputs = None

        self.model.reset()
        self.best_prompts = self.model.prompts
        self.cur_prompts = self.es.ask() + [self.model.prompts.flatten().cpu()]


@torch.jit.script
def softmax_entropy(x: torch.Tensor) -> torch.Tensor:
    """Entropy of softmax distribution from logits."""
    temprature = 1
    x = x/ temprature
    x = -(x.softmax(1) * x.log_softmax(1)).sum(1)
    return x

criterion_mse = nn.MSELoss(reduction='none')

def forward_and_get_loss(image, model:PromptViT, shift_vector, imagenet_mask):
    feature = model.layers_cls_features_with_prompts(image)
    cls_features = feature[:, -768:]
    output_for_entropy = model.vit.head(cls_features)
    if imagenet_mask is not None:
        output_for_entropy = output_for_entropy[:, imagenet_mask]

    output = output_for_entropy
    if shift_vector is not None:
        output = model.vit.head(cls_features + 1. * shift_vector)
        if imagenet_mask is not None:
            output = output[:, imagenet_mask]
    return output, output_for_entropy, feature